spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-ms
            uri: lb://user-ms
            predicates: 
              - Path=/api/v1/user/**, /user/**
            filters:
              - name: CircuitBreaker
                args:
                  name: user-ms-fallback
                  fallbackuri: forward:/fallback/userms
        - id: mail-ms
            uri:  lb://mail-ms
            predicates: 
              - Path=/api/v1/post**, /post/**
            filters:
              - name: CircuitBreaker
                args:
                  name: mail-ms-fallback
                  fallbackuri: forward:/fallback/mailms

resilience4j:
  circuitbreaker:
    configs:
      default:
          slidingWindowSize: 100
          permittedNumberOfCallsInHalfOpenState: 10
          waitDurationInOpenState: 10000
          failureRateThreshold: 60
          eventConsumerBufferSize: 10
          registerHealthIndicator: true
    instances:
        user-service:
            waitDurationInOpenState: 5000
        post-service:
            waitDurationInOpenState: 5000
            
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
    
           
             

