server:
  port: 9191
  
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: user-service-route
        uri: lb://user-service
        predicates: 
        - Path=/api/v1/user**
        filters:
        - name: FallbackController
          args:
            name: user-service
            fallbackuri: forward:/userServiceFallback
      - id: post-service-route
        uri:  lb://post-service
        predicates: 
        - Path=/api/v1/post**
        filters:
        - name: FallbackController
          args:
            name: post-service
            fallbackuri: forward:/postServiceFallback

resilience4j:
  circuitbreaker:
    configs:
      default:
          slidingWindowSize: 100
          permittedNumberOfCallsInHalfOpenState: 10
          waitDurationInOpenState: 10000
          failureRateThreshold: 60
          eventConsumerBufferSize: 10
          registerHealthIndicator: true
    instances:
        user-service:
            waitDurationInOpenState: 5000
        post-service:
            waitDurationInOpenState: 5000
            
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
    
           
             

