spring:
  platform: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/freecodecampexample
    username: root
    password: admin
    hikari:
      maximumPoolSize: 30
      connectionTimeout: 15000

spring.jpa:
  ddl-auto: create-drop
  show-sql: true
  properties.hibernate:
    dialect: org.hibernate.dialect.MySQL8Dialect
    format_sql: true
    use_sql_comments: true

server.error.include-message: always
