server:
  port: 9411
logging:
  level:
    org:
      springframework:
        web: trace
  pattern:
    level: [%X{traceId}/%X{spanId}] %-5p [%t] %C{2} - %m%n
spring:
  sleuth:
    traceId128: true
    sampler:
      probability: 1.0
    propagation-keys: user_name
